{
 "title": "Alzheimer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Displays",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM displays LIMIT 50 "
    }
   ]
  },
  {
   "title": "Posts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM posts LIMIT 50 "
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM users LIMIT 50 "
    }
   ]
  }
 ]
}